name: Build and Package

on: [push]

jobs:
  build_sdist_and_wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11 setuptools wheel build

    - name: Build source distribution and wheel
      run: |
        python -m build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 升级到 v4
      with:
        name: distributions
        path: dist/*  # 明确指定路径格式