name: Build Linux and Windows Packages

on: [push]

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 setuptools wheel build
      - name: Build sdist
        run: python -m build --sdist --no-isolation
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-package
          path: dist/*.tar.gz

  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # 仅保留 Linux 和 Windows
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install C++ build tools (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2022-workload-vctools -y  # 仅 Windows 需要安装编译工具
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 setuptools wheel build
      - name: Build Wheel
        run: python -m build --wheel --no-isolation
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl

  build_manylinux_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build manylinux wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_BUILD: "pip install pybind11"
      - name: Upload manylinux Wheels
        uses: actions/upload-artifact@v4
        with:
          name: manylinux-wheels
          path: wheelhouse/*.whl